# Generated by Django 5.0.1 on 2025-06-26 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0004_auditlog_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 일시', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 일시', verbose_name='수정일시')),
                ('slug', models.SlugField(blank=True, help_text='URL에 사용되는 고유 식별자', max_length=255, unique=True, verbose_name='슬러그')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '테스트 글',
                'verbose_name_plural': '테스트 글 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestClientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 일시', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 일시', verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(default=False, help_text='소프트 삭제 여부', verbose_name='삭제됨')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제된 일시', null=True, verbose_name='삭제일시')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP 고객')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='신용한도')),
                ('created_by', models.ForeignKey(blank=True, help_text='이 레코드를 생성한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='삭제한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='삭제자')),
                ('modified_by', models.ForeignKey(blank=True, help_text='이 레코드를 마지막으로 수정한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('organization', models.ForeignKey(help_text='이 레코드가 속한 조직', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='trainers.organization', verbose_name='조직')),
            ],
            options={
                'verbose_name': '테스트 고객 기록',
                'verbose_name_plural': '테스트 고객 기록 목록',
            },
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 일시', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 일시', verbose_name='수정일시')),
                ('name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='예산')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('completion_percentage', models.IntegerField(default=0, verbose_name='완료율')),
                ('created_by', models.ForeignKey(blank=True, help_text='이 레코드를 생성한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('modified_by', models.ForeignKey(blank=True, help_text='이 레코드를 마지막으로 수정한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '테스트 프로젝트',
                'verbose_name_plural': '테스트 프로젝트 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('active', '활성'), ('inactive', '비활성'), ('archived', '보관됨')], default='draft', help_text='현재 상태', max_length=20, verbose_name='상태')),
                ('status_changed_at', models.DateTimeField(auto_now=True, help_text='상태가 마지막으로 변경된 일시', verbose_name='상태 변경일시')),
                ('position', models.IntegerField(default=0, help_text='정렬 순서 (낮을수록 앞에 표시)', verbose_name='순서')),
                ('title', models.CharField(max_length=200, verbose_name='작업명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('created_by', models.ForeignKey(blank=True, help_text='이 레코드를 생성한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('modified_by', models.ForeignKey(blank=True, help_text='이 레코드를 마지막으로 수정한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('status_changed_by', models.ForeignKey(blank=True, help_text='상태를 변경한 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='상태 변경자')),
            ],
            options={
                'verbose_name': '테스트 작업',
                'verbose_name_plural': '테스트 작업 목록',
                'ordering': ['position'],
            },
        ),
    ]
