# Generated by Django 5.0.1 on 2025-06-13 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='harvard_step_test_heart_rate',
        ),
        migrations.AddField(
            model_name='assessment',
            name='farmer_carry_time',
            field=models.IntegerField(blank=True, help_text='Time in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='harvard_step_test_hr1',
            field=models.IntegerField(blank=True, help_text='Heart rate 1-1.5 minutes after exercise (bpm)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='harvard_step_test_hr2',
            field=models.IntegerField(blank=True, help_text='Heart rate 2-2.5 minutes after exercise (bpm)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='harvard_step_test_hr3',
            field=models.IntegerField(blank=True, help_text='Heart rate 3-3.5 minutes after exercise (bpm)', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
