# Generated by Django 5.0.1 on 2025-06-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_migrate_heart_rate_data'),
        ('trainers', '0004_auditlog_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='trainer',
            field=models.ForeignKey(help_text='The trainer who conducted this assessment', on_delete=django.db.models.deletion.CASCADE, related_name='assessments_conducted', to='trainers.trainer', verbose_name='Trainer'),
        ),
    ]
