# Generated by Django 5.0.1 on 2025-06-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='overhead_squat_forward_lean',
            field=models.BooleanField(blank=True, default=False, help_text='Excessive forward lean'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='overhead_squat_heel_lift',
            field=models.BooleanField(blank=True, default=False, help_text='Heels lift off ground'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='overhead_squat_knee_valgus',
            field=models.BooleanField(blank=True, default=False, help_text='Knees cave inward during squat'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shoulder_mobility_asymmetry',
            field=models.FloatField(blank=True, help_text='Difference between sides in cm', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shoulder_mobility_pain',
            field=models.BooleanField(blank=True, default=False, help_text='Pain during clearing test'),
        ),
    ]
