# Generated by Django 5.0.1 on 2025-06-18 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_add_movement_quality_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='injury_risk_score',
            field=models.FloatField(blank=True, help_text='Injury risk score on a 0-100 scale (0=low risk, 100=high risk)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='risk_factors',
            field=models.JSONField(blank=True, help_text='Detailed risk factors identified in the assessment', null=True),
        ),
    ]
