# Generated by Django 5.0.1 on 2025-06-18 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_add_risk_score_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('overhead_squat', 'Overhead Squat'), ('push_up', 'Push Up'), ('farmer_carry', 'Farmer Carry'), ('toe_touch', 'Toe Touch'), ('shoulder_mobility', 'Shoulder Mobility'), ('harvard_step', 'Harvard Step Test'), ('single_leg_balance', 'Single Leg Balance'), ('overall', 'Overall Score'), ('strength', 'Strength Category'), ('mobility', 'Mobility Category'), ('balance', 'Balance Category'), ('cardio', 'Cardio Category')], max_length=50)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('A', '전체')], max_length=1)),
                ('age_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age_max', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
                ('percentile_10', models.FloatField(help_text='Score at 10th percentile')),
                ('percentile_25', models.FloatField(help_text='Score at 25th percentile')),
                ('percentile_50', models.FloatField(help_text='Score at 50th percentile (median)')),
                ('percentile_75', models.FloatField(help_text='Score at 75th percentile')),
                ('percentile_90', models.FloatField(help_text='Score at 90th percentile')),
                ('source', models.CharField(help_text='Data source (e.g., ACSM Guidelines)', max_length=200)),
                ('year', models.IntegerField(help_text='Year of data collection')),
                ('sample_size', models.IntegerField(blank=True, help_text='Number of subjects in dataset', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the data')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['test_type', 'gender', 'age_min'],
                'indexes': [models.Index(fields=['test_type', 'gender', 'age_min', 'age_max'], name='assessments_test_ty_a36c40_idx')],
                'unique_together': {('test_type', 'gender', 'age_min', 'age_max')},
            },
        ),
    ]
