# Generated by Django 5.0.1 on 2025-06-18 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_normativedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='farmer_carry_percentage',
            field=models.FloatField(blank=True, help_text="Percentage of body weight used for farmer's carry", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='push_up_type',
            field=models.CharField(blank=True, choices=[('standard', '표준'), ('modified', '수정된'), ('wall', '벽')], default='standard', help_text='Type of push-up performed', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Ambient temperature in Celsius during testing', null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='test_environment',
            field=models.CharField(blank=True, choices=[('indoor', '실내'), ('outdoor', '실외')], default='indoor', help_text='Environment where tests were conducted', max_length=10, null=True),
        ),
    ]
