# Generated by Django 5.0.1 on 2025-06-18 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_add_test_variation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('push_up', 'Push Up'), ('farmer_carry', 'Farmer Carry'), ('balance', 'Single Leg Balance'), ('step_test', 'Harvard Step Test'), ('overhead_squat', 'Overhead Squat'), ('toe_touch', 'Toe Touch'), ('shoulder_mobility', 'Shoulder Mobility')], max_length=50)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('A', '전체')], default='A', max_length=1)),
                ('age_min', models.IntegerField(help_text='최소 연령', validators=[django.core.validators.MinValueValidator(0)])),
                ('age_max', models.IntegerField(help_text='최대 연령', validators=[django.core.validators.MaxValueValidator(120)])),
                ('metric_type', models.CharField(choices=[('repetitions', '반복 횟수'), ('time', '시간 (초)'), ('distance', '거리 (cm)'), ('score', '점수'), ('pfi', 'Physical Fitness Index')], help_text='측정 단위 유형', max_length=20)),
                ('excellent_threshold', models.FloatField(help_text='우수 등급 최소값')),
                ('good_threshold', models.FloatField(help_text='양호 등급 최소값')),
                ('average_threshold', models.FloatField(help_text='평균 등급 최소값')),
                ('needs_improvement_threshold', models.FloatField(default=0, help_text='개선 필요 등급 최소값 (보통 0)')),
                ('variation_type', models.CharField(blank=True, help_text='테스트 변형 유형 (예: standard, modified, wall)', max_length=50, null=True)),
                ('conditions', models.CharField(blank=True, help_text='특별 조건 (예: eyes_open, eyes_closed)', max_length=100, null=True)),
                ('name', models.CharField(help_text="기준 이름 (예: '성인 남성 푸시업 기준')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='기준 설명')),
                ('source', models.CharField(default='ACSM Guidelines', help_text='기준 출처', max_length=200)),
                ('year', models.IntegerField(default=2024, help_text='기준 제정 연도')),
                ('is_active', models.BooleanField(default=True, help_text='활성 상태')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['test_type', 'gender', 'age_min'],
                'indexes': [models.Index(fields=['test_type', 'gender', 'age_min', 'age_max'], name='assessments_test_ty_e21ca9_idx'), models.Index(fields=['test_type', 'is_active'], name='assessments_test_ty_63671b_idx')],
                'unique_together': {('test_type', 'gender', 'age_min', 'age_max', 'variation_type', 'conditions')},
            },
        ),
    ]
