# Generated by Django 5.0.1 on 2025-06-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_questioncategory_assessment_comprehensive_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='overhead_squat_arm_drop',
            field=models.BooleanField(blank=True, default=False, help_text='Arms fall forward during movement', verbose_name='팔 전방 하강'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='overhead_squat_quality',
            field=models.CharField(blank=True, choices=[('pain', '동작 중 통증 발생'), ('cannot_squat', '깊은 스쿼트 수행 불가능'), ('compensations', '보상 동작 관찰됨'), ('perfect', '완벽한 동작')], max_length=30, null=True, verbose_name='수행 품질'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shoulder_mobility_category',
            field=models.CharField(blank=True, choices=[('pain', '동작 중 통증'), ('over_1_5x', '손 간 거리가 신장 1.5배 이상'), ('1_to_1_5x', '손 간 거리가 신장 1~1.5배'), ('under_1x', '손 간 거리가 신장 1배 미만')], max_length=30, null=True, verbose_name='양손 간 거리 평가'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='toe_touch_flexibility',
            field=models.CharField(blank=True, choices=[('no_reach', '손끝이 발에 닿지 않음'), ('fingertips', '손끝이 발에 닿음'), ('palm_cover', '손바닥이 발등을 덮음'), ('palm_full', '손바닥이 발에 완전히 닿음')], max_length=30, null=True, verbose_name='유연성 평가'),
        ),
    ]
