# Generated by Django 5.0.1 on 2025-06-25 03:47

from django.db import migrations, models
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_add_movement_quality_details'),
    ]

    operations = [
        # Manual override flags for individual test scores
        migrations.AddField(
            model_name='assessment',
            name='overhead_squat_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if overhead squat score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='push_up_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if push-up score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='toe_touch_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if toe touch score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shoulder_mobility_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if shoulder mobility score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='farmer_carry_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if farmer carry score was manually entered'),
        ),
        
        # Manual score fields for tests that don't have dedicated score fields
        migrations.AddField(
            model_name='assessment',
            name='single_leg_balance_score_manual',
            field=models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0), MaxValueValidator(5)], help_text='Manual score for single leg balance test'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='single_leg_balance_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if single leg balance score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='harvard_step_test_score_manual',
            field=models.IntegerField(null=True, blank=True, validators=[MinValueValidator(0), MaxValueValidator(5)], help_text='Manual score for Harvard step test'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='harvard_step_test_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if Harvard step test score was manually entered'),
        ),
        
        # Manual override flags for category scores
        migrations.AddField(
            model_name='assessment',
            name='overall_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if overall score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='strength_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if strength score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='mobility_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if mobility score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='balance_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if balance score was manually entered'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='cardio_score_manual_override',
            field=models.BooleanField(default=False, help_text='Indicates if cardio score was manually entered'),
        ),
    ]
