# Generated by Django 5.0.1 on 2025-06-25 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_add_manual_score_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='farmer_carry_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='harvard_step_test_score_manual',
            field=models.IntegerField(blank=True, help_text='Manual score for Harvard step test', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='overhead_squat_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='push_up_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='push_up_type',
            field=models.CharField(blank=True, choices=[('standard', '표준'), ('modified', '보정됨'), ('wall', '벽')], default='standard', help_text='Type of push-up performed', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='shoulder_mobility_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='single_leg_balance_score_manual',
            field=models.IntegerField(blank=True, help_text='Manual score for single leg balance test', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='toe_touch_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
