# Generated by Django 5.0.1 on 2025-06-27 05:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_remove_refactored_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmersCarryTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('distance', models.FloatField(blank=True, help_text='Distance in meters', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('time', models.IntegerField(blank=True, help_text='Time in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, help_text='Percentage of body weight used', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('score_manual_override', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmers_carry_test', to='assessments.assessment')),
            ],
            options={
                'db_table': 'farmers_carry_tests',
            },
        ),
        migrations.CreateModel(
            name='HarvardStepTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr1', models.IntegerField(blank=True, help_text='HR 1-1.5 minutes after exercise', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)])),
                ('hr2', models.IntegerField(blank=True, help_text='HR 2-2.5 minutes after exercise', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)])),
                ('hr3', models.IntegerField(blank=True, help_text='HR 3-3.5 minutes after exercise', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(250)])),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('score_manual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('score_manual_override', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvard_step_test', to='assessments.assessment')),
            ],
            options={
                'db_table': 'harvard_step_tests',
            },
        ),
        migrations.CreateModel(
            name='OverheadSquatTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('knee_valgus', models.BooleanField(default=False)),
                ('forward_lean', models.BooleanField(default=False)),
                ('heel_lift', models.BooleanField(default=False)),
                ('arm_drop', models.BooleanField(default=False)),
                ('quality', models.CharField(blank=True, choices=[('pain', '동작 중 통증 발생'), ('cannot_squat', '깊은 스쿼트 수행 불가능'), ('compensations', '보상 동작 관찰됨'), ('perfect', '완벽한 동작')], max_length=30, null=True)),
                ('score_manual_override', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overhead_squat_test', to='assessments.assessment')),
            ],
            options={
                'db_table': 'overhead_squat_tests',
            },
        ),
        migrations.CreateModel(
            name='PushUpTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('push_up_type', models.CharField(choices=[('standard', '표준'), ('modified', '보정됨'), ('wall', '벽')], default='standard', max_length=10)),
                ('score_manual_override', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_up_test', to='assessments.assessment')),
            ],
            options={
                'db_table': 'push_up_tests',
            },
        ),
        migrations.CreateModel(
            name='ShoulderMobilityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.FloatField(blank=True, help_text='Distance in cm', null=True)),
                ('left', models.FloatField(blank=True, help_text='Distance in cm', null=True)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('pain', models.BooleanField(default=False)),
                ('asymmetry', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('pain', '동작 중 통증'), ('over_1_5x', '손 간 거리가 신장 1.5배 이상'), ('1_to_1_5x', '손 간 거리가 신장 1~1.5배'), ('under_1x', '손 간 거리가 신장 1배 미만')], max_length=30, null=True)),
                ('score_manual_override', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shoulder_mobility_test', to='assessments.assessment')),
            ],
            options={
                'db_table': 'shoulder_mobility_tests',
            },
        ),
        migrations.CreateModel(
            name='SingleLegBalanceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_eyes_open', models.IntegerField(blank=True, null=True)),
                ('left_eyes_open', models.IntegerField(blank=True, null=True)),
                ('right_eyes_closed', models.IntegerField(blank=True, null=True)),
                ('left_eyes_closed', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('score_manual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('score_manual_override', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='single_leg_balance_test', to='assessments.assessment')),
            ],
            options={
                'db_table': 'single_leg_balance_tests',
            },
        ),
        migrations.CreateModel(
            name='ToeTouchTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(blank=True, help_text='Distance in cm (negative for below toes)', null=True)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('flexibility', models.CharField(blank=True, choices=[('no_reach', '손끝이 발에 닿지 않음'), ('fingertips', '손끝이 발에 닿음'), ('palm_cover', '손바닥이 발등을 덮음'), ('palm_full', '손바닥이 발에 완전히 닿음')], max_length=30, null=True)),
                ('score_manual_override', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toe_touch_test', to='assessments.assessment')),
            ],
            options={
                'db_table': 'toe_touch_tests',
            },
        ),
    ]
