# Generated by Django 5.0.1 on 2025-06-14 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trainers', '0003_add_trainer_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('client_created', 'Client Created'), ('client_updated', 'Client Updated'), ('client_deleted', 'Client Deleted'), ('assessment_created', 'Assessment Created'), ('assessment_updated', 'Assessment Updated'), ('assessment_deleted', 'Assessment Deleted'), ('package_created', 'Package Created'), ('package_updated', 'Package Updated'), ('session_created', 'Session Created'), ('session_completed', 'Session Completed'), ('session_cancelled', 'Session Cancelled'), ('payment_recorded', 'Payment Recorded'), ('trainer_created', 'Trainer Created'), ('trainer_updated', 'Trainer Updated'), ('trainer_deactivated', 'Trainer Deactivated'), ('trainer_activated', 'Trainer Activated'), ('invitation_sent', 'Invitation Sent'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_declined', 'Invitation Declined'), ('organization_created', 'Organization Created'), ('organization_updated', 'Organization Updated'), ('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed')], max_length=50, verbose_name='Action')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('client_added', 'New Client Added'), ('assessment_completed', 'Assessment Completed'), ('session_scheduled', 'Session Scheduled'), ('payment_received', 'Payment Received'), ('trainer_invited', 'Trainer Invitation'), ('trainer_joined', 'Trainer Joined Organization'), ('organization_update', 'Organization Update'), ('system', 'System Notification')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (e.g., client, assessment)', max_length=50, null=True, verbose_name='Related Object Type')),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of the related object', null=True, verbose_name='Related Object ID')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when notification is clicked', max_length=200, null=True, verbose_name='Action URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='trainers_or_slug_6a8c1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainer',
            name='trainers_tr_organiz_8e0c25_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainer',
            name='trainers_tr_user_id_7a9e8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainer',
            name='trainers_tr_role_3f2d9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainerinvitation',
            name='trainers_tr_organiz_4e7b3c_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainerinvitation',
            name='trainers_tr_invitat_9d2f5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='trainerinvitation',
            name='trainers_tr_email_7c8a2d_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='trainers.organization', verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at'], name='trainers_au_created_89cc5a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='trainers_au_user_id_755a17_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-created_at'], name='trainers_au_organiz_59ea2e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='trainers_au_action_0e0088_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='trainers_no_user_id_98874a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='trainers_no_user_id_04aa92_idx'),
        ),
    ]
