# Generated by Django 5.0.1 on 2025-06-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('report_type', models.CharField(choices=[('summary', '요약 보고서'), ('detailed', '상세 보고서')], default='detailed', max_length=20, verbose_name='보고서 유형')),
                ('file_path', models.FileField(upload_to='reports/assessments/%Y/%m/', verbose_name='파일 경로')),
                ('file_size', models.IntegerField(default=0, verbose_name='파일 크기 (bytes)')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='assessments.assessment', verbose_name='평가')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '평가 보고서',
                'verbose_name_plural': '평가 보고서',
                'ordering': ['-generated_at'],
                'indexes': [
                    models.Index(fields=['assessment', '-generated_at'], name='reports_ass_assessm_dd7f3c_idx'),
                ],
            },
        ),
    ]