# Generated by Django 5.0.1 on 2025-06-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assessmentreport',
            new_name='reports_ass_assessm_a89d9f_idx',
            old_name='reports_ass_assessm_dd7f3c_idx',
        ),
    ]
