# Generated by Django 5.0.1 on 2025-06-15 07:28

from django.db import migrations, models


def convert_summary_to_detailed(apps, schema_editor):
    """Convert any existing summary reports to detailed type"""
    AssessmentReport = apps.get_model('reports', 'AssessmentReport')
    AssessmentReport.objects.filter(report_type='summary').update(report_type='detailed')


def reverse_conversion(apps, schema_editor):
    """Reverse migration - does nothing since we can't know which were originally summary"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_reports_ass_assessm_dd7f3c_idx_reports_ass_assessm_a89d9f_idx'),
    ]

    operations = [
        # First convert existing summary reports to detailed
        migrations.RunPython(convert_summary_to_detailed, reverse_conversion),
        # Then alter the field to remove summary option
        migrations.AlterField(
            model_name='assessmentreport',
            name='report_type',
            field=models.CharField(choices=[('detailed', '상세 보고서')], default='detailed', max_length=20, verbose_name='보고서 유형'),
        ),
    ]
