# Generated by Django 5.0.1 on 2025-06-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_auditlog_notification_and_more'),
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeauditlog',
            name='created_by',
            field=models.ForeignKey(help_text='The trainer who created this audit log', on_delete=django.db.models.deletion.CASCADE, related_name='fee_audit_logs', to='trainers.trainer', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='trainer',
            field=models.ForeignKey(help_text='The trainer who received this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trainers.trainer', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(help_text='The trainer conducting this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='trainers.trainer', verbose_name='Trainer'),
        ),
        migrations.AlterField(
            model_name='sessionpackage',
            name='trainer',
            field=models.ForeignKey(help_text='The trainer managing this package', on_delete=django.db.models.deletion.CASCADE, related_name='session_packages', to='trainers.trainer', verbose_name='Trainer'),
        ),
    ]
